/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 14.07.2026 10:59:31

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1520;
#else
constexpr int kTensorArenaSize = 496;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,156 } };
const TfArray<1, float> quant0_scale = { 1, { 1.8398709297180176, } };
const TfArray<1, int> quant0_zero = { 1, { -123 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[5] = { 36, -27, 4, -36, 30, };
const TfArray<1, int> tensor_dimension1 = { 1, { 5 } };
const TfArray<1, float> quant1_scale = { 1, { 0.0021047184709459543, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[5*10] = { 
  -5, -18, 29, 35, -43, 1, 30, -75, 39, -24, 
  63, 83, -2, 4, -60, 65, -43, 33, 50, 29, 
  -79, -54, -28, -90, -68, 69, 86, 13, 6, 22, 
  12, 127, -120, 44, -10, -28, -81, -42, -29, -28, 
  29, -45, -123, 26, -61, 12, 48, -69, -6, 67, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 5,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0097295148298144341, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { 14, 17, 36, 27, -5, -14, 21, -9, -13, 0, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 0.0037064638454467058, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  8, -67, -30, 55, 41, 10, 48, -65, 13, -16, 17, 12, 34, 75, 60, -55, -1, -16, -66, 25, 
  -69, -84, 37, 127, 15, -11, -30, -59, -36, 25, -38, -22, 42, 47, 81, 41, -20, 15, -56, -9, 
  13, -31, 3, 100, -52, -24, -63, 11, -11, 5, 26, 21, 47, -21, -1, -46, 47, -58, -58, -62, 
  18, -23, 64, 68, -61, 50, -22, -27, 6, 15, 58, 25, -42, -33, 28, -50, -7, -33, 34, 58, 
  -15, 20, -50, -26, -8, 8, -61, 12, -56, 44, 49, 12, -2, 1, 43, -40, -42, 30, 13, 7, 
  -39, 42, -30, 27, 17, -70, 26, 47, -70, -43, 34, 35, 2, 18, -37, -15, -16, 37, -34, 17, 
  78, 50, -33, -92, 57, 52, 10, -5, -37, 53, 44, 24, -35, -49, -44, 9, 44, -3, 22, -30, 
  -13, 57, 18, 57, -11, 37, 42, -59, 57, -29, -44, 59, 76, 8, -44, 22, 41, -1, -15, 45, 
  25, 40, 24, 39, 49, -12, -74, -16, -5, -1, 46, 3, 18, -60, -26, 47, -51, 29, -56, -33, 
  -17, -48, -8, -7, 21, 77, 23, 4, 38, -56, -32, 21, -83, 13, 10, -32, 8, 69, -22, 52, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0078380545601248741, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { -5, 3, 1, 6, -1, 11, 2, 2, -1, 13, 6, 0, 12, 3, 8, 5, 8, -11, -7, -1, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 0.0092948740348219872, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*156] = { 
  4, -31, 16, 22, 3, 15, 3, -33, -23, -32, -3, 36, -17, -14, -31, 27, -3, 17, -12, 4, 48, -21, 42, 12, -29, -1, -50, 2, 22, -36, 13, 7, 15, -42, -59, 12, -35, 27, 3, -53, 11, -9, -42, -8, -71, 9, -30, 3, -31, -45, -23, -24, -23, 28, 5, -13, 18, -25, 12, 24, 14, 6, 4, -14, -22, 19, 11, 6, 20, -17, 67, 34, 13, 23, 48, -33, 47, 0, 2, 14, 30, -7, -13, 15, -8, 0, -59, -13, -30, -9, 11, -1, -62, 48, -12, -37, 29, 45, -17, -28, 4, -44, 0, -10, -37, 6, 23, -13, 3, -22, 16, -7, -25, 1, -35, 45, -17, 14, -44, 54, 2, -3, 19, 47, -29, -90, 32, 0, 3, -31, -36, -34, 48, 11, 23, -1, 13, 40, -40, 11, -11, -12, -28, -22, -7, -22, -21, 16, -25, -15, -25, 12, 7, 60, 53, 15, 
  -38, -10, 28, 31, -10, -17, -9, 12, 41, 39, -24, 8, -11, 12, 22, 13, 4, -14, 42, -14, -3, 49, 76, 49, 38, 41, -16, 26, 4, 10, -7, 19, -4, 5, 27, -17, -42, -10, -9, -18, -14, -17, 37, 9, 35, 4, 0, -26, -11, 7, -49, -42, -19, 5, -25, -13, 3, -10, -26, -62, -40, 3, -17, -6, 0, 20, 93, -11, 31, -15, 105, -3, 31, 19, 44, 52, -20, -38, -7, 25, -9, -6, -21, -9, 8, 11, 18, -11, 9, -1, 7, 11, 40, 25, 12, -6, -5, -16, 13, 15, 49, 75, 29, -1, -79, -7, 36, -39, -39, -18, -28, -54, 8, -12, -26, 25, 11, 16, -7, -2, 12, -6, 10, -15, 23, 10, -2, 39, -9, 39, -36, -27, 16, 15, 34, 33, -13, -13, -25, 14, -33, 29, 9, -14, -14, 58, 17, -1, -33, -23, 9, 18, 14, 18, 11, 46, 
  15, -15, -38, -33, 10, -22, 31, 12, 37, 5, -4, -7, -39, 19, 25, 11, 20, 33, -2, -11, 16, -43, 9, -37, -43, -15, 46, 45, -38, -20, 9, 24, 37, 2, -10, -27, -28, -25, 3, -30, -12, 20, -20, -3, 46, 28, -11, -48, 5, 10, 37, 8, 3, 4, 11, -14, -6, 85, 45, 2, 46, 11, 23, -4, -11, 9, -5, 10, -12, -23, -38, -55, -39, 7, -23, -31, -50, 2, -36, -47, 16, -30, 7, -22, -6, -19, -19, -1, -16, -29, -36, 36, 30, -4, 32, 28, 20, -3, 1, 18, -53, -31, -35, -11, 36, 6, 16, 37, 3, 14, 16, 51, 28, -23, -24, -53, 13, 32, 29, -20, -24, 16, 54, -42, 16, 38, 29, 39, -17, 34, 27, -6, -1, 10, -5, 28, 15, 16, 23, -5, -10, 4, 21, 11, -57, 31, -30, -13, 29, 15, -28, -67, -40, -15, 1, 23, 
  -23, -15, 5, 25, -7, 34, 7, 12, 26, 15, 79, 58, 13, 19, -1, 11, -8, -2, 7, 5, -36, -6, -30, -23, -14, 20, -67, 15, 28, 10, -14, 8, 17, -28, -15, -32, 6, -45, -1, -46, -38, 2, 4, -4, -3, -41, -13, -48, -23, -13, -16, 24, 8, -4, -7, 11, 0, -16, 29, 2, 36, 11, 32, 13, -48, -69, 10, -29, -3, 3, -79, -57, -59, -43, -20, -3, 21, 19, 22, -29, 20, 19, -2, 0, 3, -47, 14, 27, 60, 5, 7, 15, -61, 12, 23, -14, 0, -11, 29, 6, 1, 7, 28, 17, -45, -17, 6, 7, -3, 29, -15, 14, 16, 39, -6, 12, -21, 6, -11, -30, -23, 12, 18, 31, -30, 16, 43, 17, 46, 45, -11, -37, -12, 31, 1, -19, -7, 17, 33, 33, 56, 30, 26, -34, 25, 23, 3, -12, -11, -31, -59, -60, 42, 69, 34, 47, 
  17, 28, -47, 2, 7, -16, 42, -5, -14, 13, -38, -2, -13, -25, 3, -34, 28, 34, -6, -23, -5, 19, -29, -19, 8, 0, 9, -78, -12, -33, -5, -19, 30, -30, -13, -11, -11, -21, 36, 17, -15, 40, -29, -9, 37, -12, 33, 49, -9, 17, -6, 43, -49, -18, -9, 10, -22, 17, 43, 5, -38, -46, 17, 32, -2, 15, -92, 22, -27, -4, -29, 16, 18, 9, 21, 13, -10, -14, 21, 26, -44, -18, 25, -1, 36, -16, 12, -24, 13, -15, -2, -2, 77, -43, 24, 7, 3, -19, -37, -54, -8, -37, 11, -14, 7, -22, -6, 5, 9, 5, -25, -10, -29, 3, 16, 0, -15, -56, -57, -7, 36, 1, -29, -7, -27, -4, 11, -40, -18, 20, -15, 4, -33, 3, 24, -14, 11, 26, -33, 50, 19, 9, 26, 18, 1, -127, 29, 23, -43, -32, 11, 39, -6, -25, -4, 32, 
  -14, 15, -7, -4, -25, -26, -48, 56, -61, -14, -66, -9, -19, 10, 6, 22, -25, -3, -22, 66, -8, -56, -19, -65, 14, -32, -4, -33, 1, 36, -42, -62, -28, -82, 18, -32, 4, -9, -2, 47, 35, 36, -17, 30, -49, -97, 1, -58, -9, -1, 42, -48, 31, -14, -13, 24, 0, -68, 24, 11, 3, -10, 41, 16, 14, -19, -15, 12, 38, 30, -2, -8, 38, -56, -42, -38, 31, 5, 42, -8, -49, 36, 21, 37, -47, 6, -13, -6, 13, 20, 1, 0, -45, 17, 3, -24, -20, 75, 18, -2, -17, -24, -19, -56, 23, -20, 42, -11, 3, -28, -47, -26, 14, 18, 12, 24, -4, -11, -5, -71, 0, 40, -18, 55, 38, 40, 3, -9, -15, -30, -2, 18, -40, 14, 2, 39, 11, 23, 43, 51, 42, 16, 7, -9, 45, -42, 26, 1, 32, 9, 101, 37, 45, 5, 67, 34, 
  -4, -24, -42, -23, -24, -33, -17, 19, -41, -9, -33, -41, -35, 13, -22, -4, -5, -27, 73, 42, 15, 30, -18, 17, -3, -1, 23, -16, 33, 7, 16, -8, 2, -2, 7, 39, -45, 0, -52, 34, -12, 14, -9, -5, -26, -33, 71, -20, 17, -24, -11, -16, -57, -28, 4, -2, -13, 24, 21, -17, -41, -5, 18, -32, 8, -22, -14, -20, -20, -11, 8, 31, -2, -20, 26, 0, 1, 8, 14, -60, 4, 25, -5, 23, -13, -7, 6, 9, -39, -38, -43, 37, -10, 26, 9, -17, 18, -7, -12, 2, -23, -19, 15, -2, 40, -18, -28, -3, -3, 3, 1, 21, 27, -25, -8, -24, -2, -9, -22, 7, -19, -27, -13, 16, 1, -22, -11, 5, -29, -49, 26, -27, -30, 27, 21, 23, -28, 41, 42, 45, 26, 33, 0, -37, -65, -19, 54, -4, 6, 23, 8, 48, 11, 21, -19, -38, 
  28, -34, 37, 32, 22, 20, 12, 31, 3, 14, -24, 35, -13, 14, -27, 4, 7, -4, -24, 52, 18, -28, -30, 10, 31, 29, -4, -11, -48, 11, -2, 56, 24, -42, 20, 3, 30, 48, 39, 6, 22, -21, 17, -6, 28, 4, 10, 11, 0, 13, -37, -29, -7, -53, 7, -29, -28, -18, 13, -49, -31, -40, -10, -23, 38, 30, -5, 1, -19, 7, -18, 8, 22, 34, -15, -13, 17, 41, -17, 36, 13, -25, 29, 3, 13, -28, 14, -3, 13, -10, -24, -32, 48, -4, -22, -18, -22, -35, -8, 17, -12, 22, 5, -44, -8, 0, -33, -39, 22, -15, -34, -44, 0, 16, 52, -11, 3, -3, -48, 1, 2, 29, -29, -29, 18, 22, -51, -39, -13, -20, 31, -41, -36, 17, 15, 25, -22, -4, 19, 17, 4, 63, 48, 25, -6, -24, -19, -51, 2, -5, 61, 34, 9, 8, 2, -14, 
  11, 53, 36, -10, -36, 21, -1, -26, -11, -20, -11, 14, 9, -21, 11, -14, 16, -36, 38, 4, 24, 13, 24, 3, 22, 18, 15, 18, 34, -21, 14, -33, -2, 3, -27, -9, -30, 38, -16, 13, 2, 35, -7, 6, -25, 14, -1, 7, -12, 18, -30, -30, 30, -44, 12, 39, 7, 23, 6, -9, 23, -6, 31, -14, 1, -34, 22, 37, 7, -56, -16, -7, 7, -28, -6, -27, -17, -7, -13, 43, -1, -22, -58, -7, 41, 14, 3, 13, 19, 21, 5, -22, -31, -19, 40, -11, 43, 19, 25, -12, -17, -15, -3, 22, 20, 29, 0, -10, -10, 5, -5, 36, 18, 26, 38, 40, 19, -17, 51, 13, 11, 21, 6, -7, 25, -29, 13, 43, -22, 41, -34, 6, -17, -24, -55, 8, -24, 44, 19, 44, 36, 3, 28, -14, -75, 34, -21, -67, -23, -13, 41, 29, -11, -17, -8, 29, 
  -20, -5, -34, 27, 4, 12, -62, 21, 14, 44, 33, 11, -43, -12, -37, -23, -2, 15, -56, -79, 24, 44, 47, 107, 115, 57, 8, -17, -36, 38, -23, -16, -6, 35, 18, 22, 20, 3, -19, 8, -21, 33, 16, 23, 30, -34, 22, 30, 11, -18, -2, 12, -33, -10, -41, 14, 19, 23, -67, 3, -48, -22, -38, -16, -38, -2, -2, -12, 4, 16, -20, -35, -19, -15, -34, -28, 5, 12, -52, 16, 12, 53, -34, -45, -70, 33, -25, 3, 44, 28, 22, 36, -82, -21, 18, 50, -62, -78, 3, 10, 44, -8, 13, 1, 7, 20, -53, -11, -1, -13, 7, -16, -30, -2, 26, 23, 13, 8, 49, 21, 29, -46, -18, 12, -5, 42, 57, 10, 2, 27, -10, 36, -23, 21, -49, 41, 28, -6, 3, -28, 15, -25, -3, 2, -1, 2, 58, 0, 1, 4, -33, -27, -15, -37, 26, -31, 
  28, -12, 39, -27, -23, -18, 8, 1, 12, 82, 31, 46, -16, -24, -16, -38, -15, -26, -55, -44, 6, 31, 6, 116, 115, 18, -13, -19, -8, 34, -20, 12, 52, 94, 32, 29, -1, -30, -36, -19, 2, 0, 21, -19, 47, 35, -10, -18, -5, 14, -38, -29, -17, 21, 41, 31, -16, 16, -24, -6, -1, 7, 3, -3, -19, -9, -5, -1, 28, -16, 41, -52, -38, -3, -17, 41, -3, 5, -19, 32, -9, -33, -15, -50, -43, 7, -24, 37, 27, 20, -10, 65, -34, -16, -13, -8, -67, -19, 36, 61, 67, 83, 94, 56, 21, 7, -23, -36, 30, 27, 23, 49, 31, 44, -9, 11, -22, 25, -16, 10, -22, -26, -25, -43, 46, 44, 3, 35, 54, -12, 35, -13, -29, -7, 17, 47, 15, -32, 43, 31, -29, -27, -27, -2, -22, -5, 14, 10, 50, -11, -7, 27, 14, 19, -31, -34, 
  -12, 72, -11, 2, -6, -34, 81, -21, 23, -28, 17, 26, -1, 21, 12, 27, -11, -21, 56, -13, -27, -51, 30, -33, -24, -18, 13, 25, 57, 23, 29, -4, 12, -12, -39, -33, -34, 15, 43, 23, 9, -10, 41, -12, -33, 6, -7, 24, -26, 6, -7, 73, -9, 32, 10, 43, 17, 4, 11, -39, 23, 11, -10, -32, 6, 20, -5, -1, -4, -7, -32, 22, -12, -30, 47, -10, -11, -23, 39, 58, -7, 51, -11, -9, 17, -26, -8, 5, -15, 11, 4, -40, -4, 15, 16, 0, 39, 21, -27, -39, 1, -20, 16, -9, 21, 54, 19, 71, 36, -14, 1, -2, -3, 1, -46, -12, -7, -1, 16, 55, 31, 19, 27, 2, -10, -22, -7, -19, 44, 42, -15, 16, 0, -10, 5, 11, -1, 24, -8, 30, 17, 18, 15, 23, -26, -26, 26, 23, -10, -4, 9, -13, 10, 26, 18, 27, 
  -15, 14, -17, 4, 15, -68, -38, -47, -8, 7, -22, -72, -17, 4, -41, 12, 22, -10, 11, -59, -18, 8, -52, -3, -19, -9, -12, -16, 59, -27, -52, -25, -72, 23, 18, 7, 15, -58, -55, -12, 3, -3, 4, 5, -12, 6, 48, 30, 36, 64, 46, -16, -8, 21, -17, 7, -15, 88, 16, 12, 4, -15, 11, 30, 24, -7, 0, 17, 36, 41, 15, -38, 1, -21, -46, -28, -44, 4, -24, -6, 6, 18, 5, -15, 16, 20, -14, -19, -5, -17, -31, 17, 3, 6, -4, -35, 5, -40, -9, -9, -49, 8, 2, 31, -6, 3, 27, 40, -5, -15, -18, -12, 10, -4, -32, -26, -24, -21, 44, 55, 39, 0, 50, -31, 6, 56, -17, 42, 7, 54, -39, 5, 25, 0, -2, 9, 1, -22, 34, 25, 26, -23, 13, 15, 7, 4, -16, -1, 5, -29, -31, -48, -6, -5, -13, 33, 
  2, -12, 17, -15, 0, 29, -31, 45, -1, 12, 10, -1, 6, -14, -40, -29, -66, -68, -32, -29, -25, -4, 5, -19, -31, -50, -46, -20, -31, -16, -3, -36, -29, -30, 1, 11, 15, -17, 0, 3, 31, 48, 27, -50, 71, -10, 6, 54, 56, 49, 53, 45, 7, 22, -5, -4, -13, 63, 28, -7, 12, -16, 16, -19, 33, 5, -3, -7, 2, 8, -30, -23, 7, -3, 13, -25, -12, -21, 29, -2, -1, -1, -40, -18, 14, 21, 32, 44, 5, -42, -2, 9, -23, 23, -23, -2, -12, 23, 3, -2, 13, 36, 14, -12, 5, -64, -39, 12, -1, 12, 23, -31, -10, 28, -23, 12, 12, 6, -29, -40, 15, 5, 16, -22, 57, 92, -13, 62, 34, -36, -50, -7, 11, 11, -3, -57, 23, -12, -8, -17, 26, -13, -16, -15, -35, 10, 38, -2, 37, 45, 27, -24, -14, -30, -16, -1, 
  25, -18, -25, 26, 21, -27, -17, 14, 38, 8, 36, -51, -35, 27, 44, -17, -28, -29, 35, -21, 29, 54, -24, 36, -18, -14, -10, -42, 30, 26, 84, -11, -18, 35, 18, -6, -25, 21, 57, -25, 13, 21, -17, 39, -20, -9, -37, -55, -62, -37, -29, 2, 9, -21, -66, -21, 28, -27, 17, -27, -11, -20, -46, 33, 23, 27, 8, -20, 0, 21, 9, -9, 25, 5, -10, 9, -43, -12, 2, 35, -6, -3, -26, -29, -6, -43, 34, -4, -35, -10, -15, 32, 53, -30, -33, -21, 44, 19, 21, 40, -56, 26, -18, 30, 10, -29, 20, -29, 9, -25, -19, -17, 28, 22, -39, 10, 20, -35, 10, 36, -33, -16, -14, -21, 6, 18, -8, 21, 39, -34, -25, -56, 1, -30, 27, -21, 14, -8, -47, 32, 7, 16, 1, -24, 20, -20, 20, -8, -20, -18, -16, -26, 9, 6, 2, -39, 
  16, 7, -61, 15, -2, 2, -10, -4, 16, -6, -25, 5, -8, 10, 46, -16, 26, 40, -11, 1, -52, 27, -48, 12, -9, -5, -30, 20, 47, 19, 19, -27, -38, -13, -3, 2, -10, -52, 6, 55, 20, 5, 21, -24, 37, -24, -55, -5, -35, 17, -46, -10, 30, 40, 21, -30, 30, -42, -40, 19, -17, -51, -17, -23, -8, 23, 13, 15, 4, 11, -8, 47, 48, 26, 1, 5, 5, 31, 44, 4, -37, 11, 2, 36, 37, 18, 8, 5, 1, 31, 6, 27, 7, -12, 54, 49, -62, 0, -11, 1, 16, 19, 21, -11, 13, -21, -5, -1, 24, -45, -29, -58, -56, -20, 6, -39, -20, -31, 74, 3, -16, 11, -49, -31, 6, -11, -56, -29, -37, -2, -7, -6, -25, 44, -35, -16, -25, -4, 2, 23, -11, 42, 23, 20, 18, -1, 18, -34, -39, -28, 35, 29, 0, 32, 14, 32, 
  9, 2, -37, 11, 32, -21, -20, -12, 4, -34, -43, 4, 21, 0, -57, 20, -22, -16, -11, -16, -23, -46, 15, -22, 32, -27, -27, -5, 17, 19, -27, -23, -2, -50, -36, -25, -8, -23, -2, -9, 4, -14, 9, 24, -35, -62, 0, -29, -18, -22, -26, 4, -6, 32, -2, -40, 3, -60, -10, -23, -23, 27, -27, 15, -25, 35, 22, -34, 12, 37, -15, -3, 12, 49, 39, -1, -14, 9, -1, 59, -17, 49, -37, -17, -1, 44, 5, -28, 24, 13, 4, 33, -27, -10, 19, -24, -33, -18, 32, -44, 2, -20, -12, -41, 12, 33, 43, 37, 3, -55, -27, -29, -13, -55, -53, 17, -11, 18, -67, 16, 30, 15, -26, 6, 63, 6, 11, -19, 46, 35, -27, 16, -28, 37, 6, 14, 20, -12, 37, -3, 39, 22, 43, -8, 11, -12, 36, 14, -6, 15, 14, 46, 67, 58, 37, 13, 
  -11, 2, 50, 11, 19, 14, -35, 22, -13, -84, -87, -1, 16, 22, 4, 14, -27, 23, 106, 77, 7, 12, -56, -7, -59, -22, -30, 27, 17, -17, 3, -33, -48, -87, 52, 51, 37, -12, 15, -13, -3, 1, 12, -5, -50, -61, 24, 16, 6, 4, 3, -48, 19, -32, 0, -41, 20, -116, -8, -37, -12, -42, 15, 71, 24, -14, -13, 17, -9, 9, 16, 43, 77, 45, 44, 31, 26, -8, 46, -47, -12, -32, -6, 58, 17, 37, -25, -36, -44, -6, 19, 16, 32, -13, 18, 28, 65, 67, -11, -57, -11, -31, -64, -42, -20, -84, -31, 23, 0, -53, -57, -63, 18, -31, -29, 15, 13, 41, 16, -30, -28, 25, -5, 41, -16, -12, -23, -3, -4, 2, 19, 3, -6, -2, -15, -41, 7, 23, -7, -23, -34, -35, -34, 28, 33, -11, -22, -15, -19, -16, 31, 20, -45, -32, 2, -12, 
  -26, -58, 30, -54, 8, 17, -14, -10, -36, -3, -24, 10, -10, -53, -8, -18, -4, -17, -17, 33, -7, 2, -11, 23, -19, -52, -14, -21, -59, -30, 17, -12, -21, -33, 14, 21, -1, -22, -16, -80, -7, -17, -39, 32, -58, -37, 23, -50, -59, -42, 6, -13, 3, -3, 31, -28, 19, -29, -6, 45, -15, 19, -9, 26, -1, -31, -10, -27, -9, 55, -13, 30, 11, -37, -13, -15, 53, -4, -28, -36, 4, 4, 27, 12, 30, 0, 1, 0, 0, -14, -41, -23, -8, 7, -43, -28, 15, 34, 41, -45, -40, 17, -11, -35, -54, 19, -23, -38, 28, 27, -26, 5, -46, -32, -31, -19, 20, 0, 4, -14, 24, -18, 11, 40, 12, -102, 42, -31, -33, -7, -14, 2, 23, -18, -29, 5, 44, 46, -30, 18, -9, -40, -25, -57, 19, -5, -17, -18, 27, -14, -74, -55, 10, 66, 43, -1, 
  4, 41, -1, -29, -9, -8, 7, -13, 21, 10, -27, 9, 10, 8, 40, 15, 17, -11, 3, 15, -42, -44, 4, -74, -54, -10, -22, -32, -21, 24, -2, -14, 19, -30, -1, 3, -26, 11, -4, 50, 5, -15, 17, 55, -32, -40, -27, -19, 8, 0, 52, 27, 22, -24, -31, 1, 8, -10, 12, 25, -21, 46, 8, 43, 11, -46, -30, -50, -24, 2, -78, 20, -33, -43, -20, 16, -40, -35, 6, -24, 31, 1, 33, -32, -15, 10, 32, -3, 16, -19, -31, -6, 20, 14, 25, -2, 7, -18, 17, -20, -32, 13, -2, -19, 34, -14, -37, -8, 7, 26, 53, 37, -10, -6, 29, 15, 9, 6, -43, -30, 29, -28, 31, 1, 6, 29, -24, 3, -11, 16, -37, 11, 51, -9, -25, 4, 3, 23, -28, -39, 26, -46, 2, 31, 4, 43, -30, 15, 1, 17, -48, -15, -20, -10, 5, -25, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,156 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0050519164651632309, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 0.47288060188293457, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 0.21632306277751923, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,5 } };
const TfArray<1, float> quant9_scale = { 1, { 0.56682735681533813, } };
const TfArray<1, int> quant9_zero = { 1, { -4 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 156, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 50, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 3120, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 160), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 5, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 5, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1054236_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1054236_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1054236_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1054236_3_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1054236_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
